<a href="https://colab.research.google.com/github/areebaimtiaz/FYP-process/blob/main/da2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving internship2.xlsx to internship2.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel("internship2.xlsx")
df.head()

,Intern_ID,Attendance,Tasks_Completed,Avg_Score,Feedback_Score,Performance,Unnamed: 6,1s,0s
0,1,91,10,87.0,4.6,1,NaN,43.0,37.0
1,2,84,9,80.0,4.1,1,NaN,NaN,NaN
2,3,76,7,72.0,3.6,1,NaN,NaN,NaN
3,4,61,5,57.0,2.8,0,NaN,NaN,NaN
4,5,58,4,50.0,2.4,0,NaN,NaN,NaN

In [ ]:
X = df[['Attendance', 'Tasks_Completed', 'Avg_Score', 'Feedback_Score']]
y = df['Performance']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
print(y_pred)

[1 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0]

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [ ]:
import pandas as pd

results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

results

    Actual  Predicted
30       1          1
0        1          1
22       0          0
31       0          0
18       1          1
28       1          1
10       1          1
70       0          0
4        0          0
12       0          0
49       0          0
33       1          1
67       0          0
35       1          1
68       1          1
45       0          0

In [ ]:
accuracy_score(y_test, y_pred)

1.0

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[8, 0],
       [0, 8]])

In [1]:
model.coef_

NameError: name 'model' is not defined